# Generated by Django 5.0.1 on 2024-01-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=100)),
                ('email', models.CharField(max_length=254)),
                ('mobail', models.CharField()),
                ('remarks', models.CharField()),
            ],
        ),
        
    ]
